---
driver:
  name: docker 
  socket: <%= ENV['DOCKER_HOST'] %>
driver_config:
  require_chef_omnibus: true
busser:
  sudo: true

platforms:
  - name: centos-6.5
    driver_config:
      image: ryuzee/centos:6.5

suites:
- name: default
  run_list: 
    - "recipe[nginx::default]"
  attributes: {}
